# Generated by Django 2.0.1 on 2018-01-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
